<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KRO9T2E" failures="1" tests="1" name="TestRunner2" time="70.415" errors="0" timestamp="2021-12-09T12:04:09 IST">
  <testcase classname="com.login.TC002_CreateOrganizationddTest" name="CreatOrgDropdownTest" time="39.212">
    <failure type="java.lang.AssertionError" message="expected [Cassie763] but found [Beth489]">
      <![CDATA[java.lang.AssertionError: expected [Cassie763] but found [Beth489]
at com.login.TC002_CreateOrganizationddTest.CreatOrgDropdownTest(TC002_CreateOrganizationddTest.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- CreatOrgDropdownTest -->
</testsuite> <!-- TestRunner2 -->
